# Generated by Django 4.2.6 on 2023-10-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footyMatchApp', '0003_fmuser_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmuser',
            name='username',
            field=models.CharField(default=''),
        ),
    ]
