# Generated by Django 4.2.6 on 2023-10-30 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footyMatchApp', '0004_fmuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fmuser',
            name='username',
        ),
    ]
