# Generated by Django 3.2.23 on 2023-11-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footyMatchApp', '0007_team_remove_fmuser_favorites_fmuser_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fmuser',
            name='favorites',
        ),
        migrations.AddField(
            model_name='fmuser',
            name='favorites',
            field=models.CharField(default='No Favorites Set', max_length=10000),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
