# Generated by Django 4.2.6 on 2023-11-03 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footyMatchApp', '0009_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fmuser',
            name='favorites',
        ),
    ]
