# Generated by Django 4.2.6 on 2023-11-03 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footyMatchApp', '0011_alter_favorites_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FMUser',
        ),
    ]
